
export interface IElement {
    name: string;
    radius: number;
}

export type TPeriodicTable = Record<string, IElement>;

export const PeriodicTable: TPeriodicTable = {
  H:  { radius: 0.38, name: "Hydrogen" },
  He: { radius: 0.32, name: "Helium" },
  Li: { radius: 1.34, name: "Lithium" },
  Be: { radius: 0.90, name: "Beryllium" },
  B:  { radius: 0.82, name: "Boron" },
  C:  { radius: 0.77, name: "Carbon" },
  N:  { radius: 0.75, name: "Nitrogen" },
  O:  { radius: 0.73, name: "Oxygen" },
  F:  { radius: 0.71, name: "Fluorine" },
  Ne: { radius: 0.69, name: "Neon" },

  Na: { radius: 1.54, name: "Sodium" },
  Mg: { radius: 1.30, name: "Magnesium" },
  Al: { radius: 1.18, name: "Aluminum" },
  Si: { radius: 1.11, name: "Silicon" },
  P:  { radius: 1.06, name: "Phosphorus" },
  S:  { radius: 1.02, name: "Sulfur" },
  Cl: { radius: 0.99, name: "Chlorine" },
  Ar: { radius: 0.97, name: "Argon" },

  K:  { radius: 1.96, name: "Potassium" },
  Ca: { radius: 1.74, name: "Calcium" },
  Sc: { radius: 1.44, name: "Scandium" },
  Ti: { radius: 1.32, name: "Titanium" },
  V:  { radius: 1.22, name: "Vanadium" },
  Cr: { radius: 1.18, name: "Chromium" },
  Mn: { radius: 1.17, name: "Manganese" },
  Fe: { radius: 1.17, name: "Iron" },
  Co: { radius: 1.16, name: "Cobalt" },
  Ni: { radius: 1.15, name: "Nickel" },
  Cu: { radius: 1.17, name: "Copper" },
  Zn: { radius: 1.25, name: "Zinc" },
  Ga: { radius: 1.26, name: "Gallium" },
  Ge: { radius: 1.22, name: "Germanium" },
  As: { radius: 1.19, name: "Arsenic" },
  Se: { radius: 1.20, name: "Selenium" },
  Br: { radius: 1.20, name: "Bromine" },
  Kr: { radius: 1.16, name: "Krypton" },

  Rb: { radius: 2.10, name: "Rubidium" },
  Sr: { radius: 1.85, name: "Strontium" },
  Y:  { radius: 1.63, name: "Yttrium" },
  Zr: { radius: 1.54, name: "Zirconium" },
  Nb: { radius: 1.47, name: "Niobium" },
  Mo: { radius: 1.38, name: "Molybdenum" },
  Tc: { radius: 1.28, name: "Technetium" },
  Ru: { radius: 1.25, name: "Ruthenium" },
  Rh: { radius: 1.25, name: "Rhodium" },
  Pd: { radius: 1.20, name: "Palladium" },
  Ag: { radius: 1.28, name: "Silver" },
  Cd: { radius: 1.36, name: "Cadmium" },
  In: { radius: 1.42, name: "Indium" },
  Sn: { radius: 1.40, name: "Tin" },
  Sb: { radius: 1.40, name: "Antimony" },
  Te: { radius: 1.36, name: "Tellurium" },
  I:  { radius: 1.33, name: "Iodine" },
  Xe: { radius: 1.31, name: "Xenon" },

  Cs: { radius: 2.25, name: "Cesium" },
  Ba: { radius: 1.98, name: "Barium" },
  La: { radius: 1.69, name: "Lanthanum" },
  Ce: { radius: 1.65, name: "Cerium" },
  Pr: { radius: 1.65, name: "Praseodymium" },
  Nd: { radius: 1.64, name: "Neodymium" },
  Pm: { radius: 1.63, name: "Promethium" },
  Sm: { radius: 1.62, name: "Samarium" },
  Eu: { radius: 1.61, name: "Europium" },
  Gd: { radius: 1.60, name: "Gadolinium" },
  Tb: { radius: 1.59, name: "Terbium" },
  Dy: { radius: 1.58, name: "Dysprosium" },
  Ho: { radius: 1.57, name: "Holmium" },
  Er: { radius: 1.56, name: "Erbium" },
  Tm: { radius: 1.55, name: "Thulium" },
  Yb: { radius: 1.54, name: "Ytterbium" },
  Lu: { radius: 1.53, name: "Lutetium" },

  Hf: { radius: 1.52, name: "Hafnium" },
  Ta: { radius: 1.51, name: "Tantalum" },
  W:  { radius: 1.50, name: "Tungsten" },
  Re: { radius: 1.49, name: "Rhenium" },
  Os: { radius: 1.48, name: "Osmium" },
  Ir: { radius: 1.47, name: "Iridium" },
  Pt: { radius: 1.46, name: "Platinum" },
  Au: { radius: 1.45, name: "Gold" },
  Hg: { radius: 1.44, name: "Mercury" },
  Tl: { radius: 1.43, name: "Thallium" },
  Pb: { radius: 1.42, name: "Lead" },
  Bi: { radius: 1.41, name: "Bismuth" },
  Po: { radius: 1.40, name: "Polonium" },
  At: { radius: 1.39, name: "Astatine" },
  Rn: { radius: 1.38, name: "Radon" },

  Fr: { radius: 1.37, name: "Francium" },
  Ra: { radius: 1.36, name: "Radium" },
  Ac: { radius: 1.35, name: "Actinium" },
  Th: { radius: 1.34, name: "Thorium" },
  Pa: { radius: 1.33, name: "Protactinium" },
  U:  { radius: 1.32, name: "Uranium" },
  Np: { radius: 1.31, name: "Neptunium" },
  Pu: { radius: 1.30, name: "Plutonium" },
  Am: { radius: 1.29, name: "Americium" },
  Cm: { radius: 1.28, name: "Curium" },
  Bk: { radius: 1.27, name: "Berkelium" },
  Cf: { radius: 1.26, name: "Californium" },
  Es: { radius: 1.25, name: "Einsteinium" },
  Fm: { radius: 1.24, name: "Fermium" },
  Md: { radius: 1.23, name: "Mendelevium" },
  No: { radius: 1.22, name: "Nobelium" },
  Lr: { radius: 1.21, name: "Lawrencium" },

  Rf: { radius: 1.20, name: "Rutherfordium" },
  Db: { radius: 1.19, name: "Dubnium" },
  Sg: { radius: 1.18, name: "Seaborgium" },
  Bh: { radius: 1.17, name: "Bohrium" },
  Hs: { radius: 1.16, name: "Hassium" },
  Mt: { radius: 1.15, name: "Meitnerium" },
  Ds: { radius: 1.14, name: "Darmstadtium" },
  Rg: { radius: 1.13, name: "Roentgenium" },
  Cn: { radius: 1.12, name: "Copernicium" },
  Nh: { radius: 1.11, name: "Nihonium" },
  Fl: { radius: 1.10, name: "Flerovium" },
  Mc: { radius: 1.09, name: "Moscovium" },
  Lv: { radius: 1.08, name: "Livermorium" },
  Ts: { radius: 1.07, name: "Tennessine" },
  Og: { radius: 1.06, name: "Oganesson" },
} as const;
