/**
 * Cube + CHGCAR integration tests.
 *
 * These exercise the **TS integration boundary**: format inference,
 * reader dispatch in `openTextReader`, the `DrawIsosurfaceModifier`'s
 * auto-attach predicate, and the marching-cubes path the modifier
 * drives. Parser correctness across the full fixture set is covered by
 * the Rust-side `tests/test_io/test_{cube,chgcar}.rs` tests; loading
 * those large fixtures from a browser test environment is impractical
 * (no FS access), so we use a minimal inlined cube fixture plus
 * synthetic in-memory frames.
 */

import { Box, Frame } from "@molcrafts/molrs";
import { describe, expect, it } from "@rstest/core";
import { marchingCubes } from "../src/algo/marching_cubes";
import {
  FILE_FORMAT_REGISTRY,
  getAllAcceptExtensions,
  inferFormatFromFilename,
} from "../src/io/formats";
import { loadTextTrajectory } from "../src/io/reader";
import { applyAutoAttach } from "../src/pipeline/auto_attach";
import { DrawIsosurfaceModifier } from "../src/pipeline/draw_isosurface";
import { ModifierPipeline } from "../src/pipeline/pipeline";
import "./setup_wasm";

// Smallest legal cube file — 1×1×5 grid, 2 atoms, density sequence
// `[-1e2, -1e-2, 0, 1e-2, 1e2]`. Mirrors the `valtest.cube` Rust fixture.
const VALTEST_CUBE = `File generated by hand
Values are for testing for proper thresholding
    2   -2.000000   -2.000000   -2.000000
    1    1.000000    0.000000    0.000000
    1    0.000000    1.000000    0.000000
    5    0.000000    0.000000    1.000000
    1    0.000000    0.000000    0.000000    0.000000
    1    0.000000    0.000000    0.000000    1.000000
 -1.00000E+02 -1.00000E-02  0.00000E+00  1.00000E-02  1.00000E+02
`;

/**
 * Build a synthetic frame that carries a 3-D grid block + simbox. The
 * field is a centered Gaussian, which guarantees marching cubes
 * produces a closed surface at the auto-picked default isovalue.
 */
function syntheticGridFrame(nx: number, ny: number, nz: number): Frame {
  const frame = new Frame();
  const grid = frame.createBlock("grid");

  const data = new Float64Array(nx * ny * nz);
  const cx = (nx - 1) / 2;
  const cy = (ny - 1) / 2;
  const cz = (nz - 1) / 2;
  const sigma2 = (Math.min(nx, ny, nz) / 4) ** 2;
  for (let ix = 0; ix < nx; ix++) {
    for (let iy = 0; iy < ny; iy++) {
      for (let iz = 0; iz < nz; iz++) {
        const dx = ix - cx;
        const dy = iy - cy;
        const dz = iz - cz;
        data[ix * ny * nz + iy * nz + iz] = Math.exp(
          -(dx * dx + dy * dy + dz * dz) / sigma2,
        );
      }
    }
  }
  grid.setColF("density", data);
  grid.setShape(new Uint32Array([nx, ny, nz]));

  // Cubic 10 Å box, origin at zero, finite (non-PBC).
  const box = Box.cube(
    new Float64Array([10.0]),
    new Float64Array([0, 0, 0]),
    false,
    false,
    false,
  );
  frame.simbox = box;

  // Trivial atoms block — present so DrawAtomModifier doesn't reject
  // the frame in pipeline tests, but content is not load-bearing.
  const atoms = frame.createBlock("atoms");
  atoms.setColF("x", new Float64Array([0]));
  atoms.setColF("y", new Float64Array([0]));
  atoms.setColF("z", new Float64Array([0]));
  atoms.setColStr("element", ["C"]);
  return frame;
}

describe("format registry", () => {
  it("registers cube and chgcar entries", () => {
    const formats = FILE_FORMAT_REGISTRY.map((d) => d.format);
    expect(formats).toContain("cube");
    expect(formats).toContain("chgcar");
  });

  it("infers cube from .cube and .cub", () => {
    expect(inferFormatFromFilename("water.cube")).toBe("cube");
    expect(inferFormatFromFilename("orbitals.cub")).toBe("cube");
    expect(inferFormatFromFilename("WATER.CUBE")).toBe("cube"); // case-insensitive
  });

  it("infers chgcar from extension and from canonical CHGCAR basename", () => {
    expect(inferFormatFromFilename("foo.chgcar")).toBe("chgcar");
    expect(inferFormatFromFilename("CHGCAR")).toBe("chgcar");
    expect(inferFormatFromFilename("CHGCAR_sum")).toBe("chgcar");
    expect(inferFormatFromFilename("/path/to/CHGCAR")).toBe("chgcar");
    expect(inferFormatFromFilename("chgcar")).toBe(null); // lowercase basename rejected
  });

  it("includes new extensions in the accept attribute", () => {
    const accept = getAllAcceptExtensions();
    expect(accept).toContain(".cube");
    expect(accept).toContain(".cub");
    expect(accept).toContain(".chgcar");
  });

  it("returns null for unknown extensions", () => {
    expect(inferFormatFromFilename("foo.bar")).toBe(null);
    expect(inferFormatFromFilename("noext")).toBe(null);
  });
});

describe("loadTextTrajectory cube path", () => {
  it("loads the inlined valtest cube as a 1-frame trajectory with grid block", () => {
    const bundle = loadTextTrajectory(VALTEST_CUBE, "valtest.cube");
    try {
      expect(bundle.trajectory.length).toBe(1);
      const frame = bundle.trajectory.get(0);
      expect(frame).toBeDefined();
      const grid = frame?.getBlock("grid");
      expect(grid).toBeDefined();
      const shape = grid ? Array.from(grid.shape()) : [];
      expect(shape).toEqual([1, 1, 5]);
      expect(frame?.simbox).toBeDefined();

      const atoms = frame?.getBlock("atoms");
      expect(atoms?.nrows()).toBe(2);

      const density = grid?.copyColF("density");
      expect(density?.length).toBe(5);
      expect(density?.[0]).toBeCloseTo(-1e2, 6);
      expect(density?.[4]).toBeCloseTo(1e2, 6);
    } finally {
      bundle.dispose();
    }
  });

  it("dispatches CHGCAR-named files to the chgcar reader", () => {
    // We can't ship a multi-MB CHGCAR fixture inline, so we just verify
    // the dispatch path doesn't reject the basename. A tiny invalid
    // payload should make the chgcar parser error — if the cube parser
    // had been picked instead the error message would mention "Cube".
    let err: unknown = null;
    try {
      loadTextTrajectory("not a real chgcar", "CHGCAR");
    } catch (e) {
      err = e;
    }
    expect(err).not.toBeNull();
    expect(String(err)).toMatch(/CHGCAR/i);
  });
});

describe("DrawIsosurfaceModifier.matches", () => {
  it("returns true for a frame with a 3-D grid block and simbox", () => {
    const frame = syntheticGridFrame(8, 8, 8);
    expect(new DrawIsosurfaceModifier().matches(frame)).toBe(true);
  });

  it("returns false for an atoms-only frame (no grid)", () => {
    const frame = new Frame();
    const atoms = frame.createBlock("atoms");
    atoms.setColF("x", new Float64Array([0]));
    atoms.setColF("y", new Float64Array([0]));
    atoms.setColF("z", new Float64Array([0]));
    atoms.setColStr("element", ["C"]);
    expect(new DrawIsosurfaceModifier().matches(frame)).toBe(false);
  });

  it("returns false when grid has no simbox", () => {
    const frame = new Frame();
    const grid = frame.createBlock("grid");
    grid.setColF("density", new Float64Array(8));
    grid.setShape(new Uint32Array([2, 2, 2]));
    // No simbox set → reject.
    expect(new DrawIsosurfaceModifier().matches(frame)).toBe(false);
  });
});

describe("auto-attach integration", () => {
  it("attaches Draw Isosurface for grid-bearing frames", () => {
    const pipeline = new ModifierPipeline();
    const attached = applyAutoAttach(pipeline, syntheticGridFrame(8, 8, 8));
    expect(attached).toContain(DrawIsosurfaceModifier.NAME);
  });

  it("does not attach Draw Isosurface for atoms-only frames", () => {
    const pipeline = new ModifierPipeline();
    const frame = new Frame();
    const atoms = frame.createBlock("atoms");
    atoms.setColF("x", new Float64Array([0]));
    atoms.setColF("y", new Float64Array([0]));
    atoms.setColF("z", new Float64Array([0]));
    atoms.setColStr("element", ["C"]);
    const attached = applyAutoAttach(pipeline, frame);
    expect(attached).not.toContain(DrawIsosurfaceModifier.NAME);
  });

  it("'grid' is among the frame's blockNames on a grid-bearing frame", () => {
    // Regression: the pipeline phase-A merge consults
    // `frame.blockNames()` to decide which blocks to propagate. If a
    // grid-bearing frame ever stopped reporting "grid" there, the
    // isosurface modifier would see an empty frame at apply() time
    // even though matches() was true.
    const frame = syntheticGridFrame(4, 4, 4);
    const blocks = frame.blockNames();
    expect(blocks).toContain("grid");
    expect(blocks).toContain("atoms");
  });
});

describe("DrawIsosurfaceModifier.availableChannels", () => {
  it("lists every grid column for the channel selector", () => {
    const frame = new Frame();
    const grid = frame.createBlock("grid");
    grid.setColF("total", new Float64Array(8));
    grid.setColF("diff", new Float64Array(8));
    grid.setShape(new Uint32Array([2, 2, 2]));
    const cols = DrawIsosurfaceModifier.availableChannels(frame).sort();
    expect(cols).toEqual(["diff", "total"]);
  });

  it("returns empty when frame has no grid block", () => {
    const frame = new Frame();
    expect(DrawIsosurfaceModifier.availableChannels(frame)).toEqual([]);
  });
});

describe("marching cubes from grid block", () => {
  it("produces a closed isosurface for a centered Gaussian field", () => {
    const nx = 16;
    const ny = 16;
    const nz = 16;
    const frame = syntheticGridFrame(nx, ny, nz);
    const grid = frame.getBlock("grid");
    expect(grid).toBeDefined();
    if (!grid) return;

    const data = grid.copyColF("density");
    expect(data).toBeDefined();
    if (!data) return;

    // Use the same iso heuristic the modifier picks by default.
    let max = 0;
    for (let i = 0; i < data.length; i++) {
      const v = Math.abs(data[i]);
      if (v > max) max = v;
    }
    const isovalue = 0.5 * max; // Gaussian half-max → comfortable closed surface

    // Identity cell so we can verify mesh non-emptiness without
    // worrying about the simbox transform — marchingCubes is geometry-only.
    const cell = new Float64Array([nx, 0, 0, 0, ny, 0, 0, 0, nz]);
    const origin = new Float64Array([0, 0, 0]);
    const mesh = marchingCubes(data, [nx, ny, nz], cell, origin, isovalue);
    expect(mesh.positions.length).toBeGreaterThan(0);
    expect(mesh.indices.length).toBeGreaterThan(0);
    expect(mesh.normals.length).toBe(mesh.positions.length);
  });
});
