/**
 * Regression: cube load golden (public IO).
 *
 * Provenance: valtest.cube-style fixture from molrs; goldens 2026-07-22.
 * Run: npm run test:regressions
 */
import { describe, expect, it } from "@rstest/core";
import { loadTextTrajectory } from "../core/src/io/reader";

const VALTEST_CUBE = `File generated by hand
Values are for testing for proper thresholding
    2   -2.000000   -2.000000   -2.000000
    1    1.000000    0.000000    0.000000
    1    0.000000    1.000000    0.000000
    5    0.000000    0.000000    1.000000
    1    0.000000    0.000000    0.000000    0.000000
    1    0.000000    0.000000    0.000000    1.000000
 -1.00000E+02 -1.00000E-02  0.00000E+00  1.00000E-02  1.00000E+02
`;

describe("regression: cube load", () => {
  it("loads valtest cube: shape [1,1,5], 2 atoms, density ends", () => {
    const bundle = loadTextTrajectory(VALTEST_CUBE, "valtest.cube");
    try {
      expect(bundle.trajectory.length).toBe(1);
      const frame = bundle.trajectory.get(0);
      const grid = frame?.getBlock("grid");
      expect(Array.from(grid?.shape() ?? [])).toEqual([1, 1, 5]);
      expect(frame?.getBlock("atoms")?.nrows()).toBe(2);
      const density = grid?.copyColF("density");
      expect(density?.[0]).toBeCloseTo(-1e2, 6);
      expect(density?.[4]).toBeCloseTo(1e2, 6);
    } finally {
      bundle.dispose();
    }
  });

  it("dispatches CHGCAR basename to chgcar reader (error names CHGCAR)", () => {
    let err: unknown = null;
    try {
      loadTextTrajectory("not a real chgcar", "CHGCAR");
    } catch (e) {
      err = e;
    }
    expect(err).not.toBeNull();
    expect(String(err)).toMatch(/CHGCAR/i);
  });
});
